"use client";
import {useEffect,useRef,useState} from "react";
import {begin,createState,emptyInput,rematch,step,type Hero,type Input,type State} from "../lib/game";
import {Renderer} from "../lib/render";
import {RoomNetwork,roomRequest,type Session,type Member} from "../lib/network";
import { CHARACTERS, DEFAULT_ROSTER, ROSTER_INFO, defaultOpponent, heroesOf, isBoss, isHero, isRoster, portrait, rosterOf, statsOf, styleOf, type Roster } from "../lib/characters";
import {createBrain,ladder,think,DIFFICULTIES,type Brain,type Difficulty} from "../lib/ai";
import {Sfx} from "../lib/audio";
const title=(h:string)=>isHero(h)?CHARACTERS[h].name:"LUTADOR";
type RoomInfo={code:string;hostName:string;hostHero:Hero;roster:Roster;rivalName:string|null;rivalHero:Hero|null;spectators:number};
type OpenRoom={code:string;hostName:string;hostHero:Hero;roster:Roster;spectators:number;created:number};
// Solo ladder: beat every other fighter. `result` is what the overlay is showing between fights;
// `losses` and `startedAt` feed the record table; the run is saved in localStorage after every fight.
type Arcade={ladder:Hero[];stage:number;result:"fight"|"won"|"lost"|"champion";difficulty:Difficulty;losses:number;startedAt:number;hero:Hero};
type Record_={hero:Hero;losses:number;time:number;difficulty:Difficulty;date:number};
const keyMap:Record<string,keyof Input>={KeyA:"left",KeyD:"right",KeyW:"jump",KeyS:"down",KeyJ:"punch",KeyK:"kick",KeyL:"block",KeyI:"special",KeyU:"grab"};
const store={get<T>(k:string,fallback:T):T{try{const v=localStorage.getItem(k);return v?JSON.parse(v) as T:fallback}catch{return fallback}},set(k:string,v:unknown){try{localStorage.setItem(k,JSON.stringify(v))}catch{}},del(k:string){try{localStorage.removeItem(k)}catch{}}};
const clock=(ms:number)=>Math.floor(ms/60000)+":"+String(Math.floor(ms/1000)%60).padStart(2,"0");
/** A remote viewer draws one snapshot behind, sliding fighters and shots between the last two states it received. */
function interpolate(prev:State,curr:State,alpha:number):State{
 if(prev.tick>=curr.tick||prev.phase!==curr.phase)return curr;const a=Math.max(0,Math.min(1,alpha));
 const fighters=curr.fighters.map((f,i)=>{const p=prev.fighters[i];return p.hero===f.hero?{...f,x:p.x+(f.x-p.x)*a,y:p.y+(f.y-p.y)*a}:f}) as State["fighters"];
 const projectiles=curr.projectiles.map(q=>{const p=prev.projectiles.find(v=>v.id===q.id);return p?{...q,x:p.x+(q.x-p.x)*a}:q});
 return {...curr,fighters,projectiles};
}
export default function Home(){
 const [hero,setHero]=useState<Hero>("marica"),[name,setName]=useState(""),[code,setCode]=useState(""),[session,setSession]=useState<Session|null>(null),[members,setMembers]=useState<Member[]>([]),[busy,setBusy]=useState(false),[error,setError]=useState(""),[copied,setCopied]=useState(""),[loaded,setLoaded]=useState(false),[sound,setSound]=useState(false),[direct,setDirect]=useState(false),[onlineError,setOnlineError]=useState(""),[fallback,setFallback]=useState(false),[view,setView]=useState<State>(createState()),[training,setTraining]=useState(false),[latency,setLatency]=useState(0),[room,setRoom]=useState<RoomInfo|null>(null),[arcade,setArcade]=useState<Arcade|null>(null),[roster,setRoster]=useState<Roster>(DEFAULT_ROSTER),[mode,setMode]=useState<"arcade"|"duelo">("arcade");
 const [difficulty,setDifficulty]=useState<Difficulty>("normal"),[saved,setSaved]=useState<Arcade|null>(null),[records,setRecords]=useState<Record_[]>([]),[vs,setVs]=useState<{a:Hero;b:Hero;stage:number;total:number}|null>(null),[openRooms,setOpenRooms]=useState<OpenRoom[]>([]),[isPublic,setIsPublic]=useState(true),[resume,setResume]=useState<Session|null>(null);
 const held=useRef<Input>(emptyInput()),pulse=useRef<Partial<Record<keyof Input,number>>>({}); const canvas=useRef<HTMLCanvasElement>(null),stage=useRef<HTMLDivElement>(null),state=useRef<State>(createState()),input=useRef<Input>(emptyInput()),net=useRef<RoomNetwork|null>(null),renderer=useRef<Renderer|null>(null),sfx=useRef<Sfx|null>(null),sessionRef=useRef<Session|null>(null),trainingRef=useRef(false),visible=useRef(true),rivalId=useRef<string|null>(null),autoWatch=useRef(""),arcadeRef=useRef<Arcade|null>(null),brain=useRef<Brain>(createBrain()),snaps=useRef<{prev:State|null;curr:State|null;prevAt:number;currAt:number}>({prev:null,curr:null,prevAt:0,currAt:0}),vsTimer=useRef<ReturnType<typeof setTimeout>|null>(null);
 const audio=()=>sfx.current??(sfx.current=new Sfx());
 useEffect(()=>{audio().enable(sound)},[sound]);
 // The roster (?elenco=rockstar) picks which cast is loaded and offered; the default is the original crew.
 function chooseRoster(r:Roster){setRoster(r);setHero(h=>rosterOf(h)===r?h:heroesOf(r)[0]);history.replaceState(null,"",r===DEFAULT_ROSTER?location.pathname+location.search.replace(/[?&]elenco=[^&]*/,"").replace(/^&/,"?"):(location.search.includes("sala=")?location.search.replace(/[?&]elenco=[^&]*/,"")+"&elenco="+r:"?elenco="+r))}
 useEffect(()=>{const q=new URLSearchParams(location.search);const sala=(q.get("sala")||"").toUpperCase();if(sala){setCode(sala);setMode("duelo")}if(q.get("assistir")==="1"&&/^[A-Z2-9]{8}$/.test(sala))autoWatch.current=sala;const r=q.get("elenco");if(isRoster(r)&&r!==DEFAULT_ROSTER){setRoster(r);setHero(heroesOf(r)[0])}
  setDifficulty(store.get<Difficulty>("arcade:difficulty","normal"));
  // A session saved less than 15 minutes ago for the room in the URL is resumed instead of joined again.
  const kept=sala?store.get<{s:Session;at:number}|null>("session:"+sala,null):null;if(kept&&Date.now()-kept.at<900000&&isHero(kept.s.hostHero)){setResume(kept.s);const rr=rosterOf(kept.s.hostHero);if(rr!==r){setRoster(rr);history.replaceState(null,"","?sala="+sala+(rr!==DEFAULT_ROSTER?"&elenco="+rr:""))}}
  return()=>net.current?.close()},[]);
 useEffect(()=>{const wanted=new URLSearchParams(location.search).get("elenco");if(isRoster(wanted)&&wanted!==roster)return;/* the URL roster is about to be applied; do not download the default one first */const r=renderer.current??(renderer.current=new Renderer());let alive=true;setLoaded(false);r.load(roster).then(()=>{if(alive)setLoaded(true)}).catch(()=>setError("Não foi possível carregar os personagens. Recarregue a página."));return()=>{alive=false}},[roster]);
 useEffect(()=>{document.title=ROSTER_INFO[roster].title+" — "+heroesOf(roster).map(h=>CHARACTERS[h].name).join(", ")},[roster]);
 // Saved arcade run and record table for the roster on screen.
 useEffect(()=>{setSaved(store.get<Arcade|null>("arcade:progress:"+roster,null));setRecords(store.get<Record_[]>("arcade:records:"+roster,[]))},[roster,arcade]);
 // A spectator link (?sala=…&assistir=1) joins the stands as soon as the art is ready.
 useEffect(()=>{if(!loaded||!autoWatch.current)return;const sala=autoWatch.current;autoWatch.current="";connect("join",true,sala)},[loaded]);
 useEffect(()=>{if(!loaded||!resume)return;const s=resume;setResume(null);roomRequest({op:"sync",id:s.id},s.token).then(()=>attach(s)).catch(()=>{store.del("session:"+s.code);setError("A sessão anterior terminou. Entre de novo na sala.")})},[loaded,resume]);
 // Open rooms for the duel lobby, refreshed while the list is on screen.
 useEffect(()=>{if(mode!=="duelo"||session||training||arcade)return;let alive=true;const load=()=>roomRequest({op:"list"}).then((d:{rooms:OpenRoom[]})=>{if(alive)setOpenRooms(d.rooms)}).catch(()=>{});load();const t=setInterval(load,6000);return()=>{alive=false;clearInterval(t)}},[mode,session,training,arcade]);
 // Music while a fight is on screen.
 const active=!!session||training||!!arcade;
 useEffect(()=>{const a=audio();if(active&&sound)a.music(roster);else a.stopMusic();return()=>a.stopMusic()},[active,sound,roster]);
 useEffect(()=>{
  let frame=0,last=performance.now(),acc=0,lastUi=0,lastSend=0,previousHp=400;
  function tick(now:number){for(const k of Object.keys(pulse.current) as (keyof Input)[]){if(!held.current[k] && now >= (pulse.current[k]||0)){input.current[k]=false;delete pulse.current[k]}} const dt=Math.min((now-last)/1000,.1);last=now;const n=net.current,s=state.current,isHost=sessionRef.current?.slot===0;
   // A new rival (different member) always starts a fresh match, whatever hero they picked.
   if(isHost){const rival=n?.members.find(m=>m.slot===1);if(rival&&rival.id!==rivalId.current){rivalId.current=rival.id;const fresh=createState(s.fighters[0].hero,isHero(rival.hero)?rival.hero:undefined);fresh.tick=s.tick+1;Object.assign(s,fresh)}s.connected=!!n?.opponentPresent;s.paused=!visible.current||!s.connected;if(s.connected&&s.phase==="waiting")begin(s)}
   const arc=arcadeRef.current;
   if(trainingRef.current||(arc&&!vsTimer.current)){s.connected=true;s.paused=!visible.current;if(s.phase==="waiting")begin(s)}
   if(isHost||trainingRef.current||arc){acc+=dt;const remote=n&&Date.now()-n.remoteAt<700?n.remoteInput:emptyInput();while(acc>=1/60){step(s,[input.current,arc?think(s,1,brain.current,1/60,arc.stage):remote]);for(const e of s.events)audio().play(e);acc-=1/60}if(n&&now-lastSend>33){n.broadcast(s);lastSend=now}}
   if(arc&&arc.result==="fight"&&s.phase==="over"){arc.result=s.winner===0?(arc.stage>=arc.ladder.length-1?"champion":"won"):"lost";if(arc.result==="lost")arc.losses++;saveRun(arc);setArcade({...arc})}
   else if(sessionRef.current?.slot===1&&n&&now-lastSend>33){n.sendInput(input.current);lastSend=now}
   const ctx=canvas.current?.getContext("2d");
   if(ctx&&renderer.current?.ready){const sn=snaps.current;const shown=!isHost&&sessionRef.current&&sn.prev&&sn.curr?interpolate(sn.prev,sn.curr,(now-sn.currAt)/Math.max(16,sn.currAt-sn.prevAt)):s;renderer.current.draw(ctx,shown,now/1000)}
   if(!isHost&&sessionRef.current){const hp=s.fighters[0].hp+s.fighters[1].hp;if(hp<previousHp&&!s.events.length)audio().play("hit");previousHp=hp}
   if(now-lastUi>90){lastUi=now;setView({...s,fighters:s.fighters.map(f=>({...f})) as State["fighters"]})}
   frame=requestAnimationFrame(tick);
  }
  frame=requestAnimationFrame(tick);
  const onKey=(e:KeyboardEvent)=>{if((e.target as HTMLElement)?.closest("input,textarea,select"))return;const key=keyMap[e.code];if(!key||(!sessionRef.current&&!trainingRef.current&&!arcadeRef.current)||sessionRef.current?.slot===null)return;e.preventDefault();action(key,e.type==="keydown")};
  const reset=()=>{held.current=emptyInput();pulse.current={};input.current=emptyInput();net.current?.sendInput(input.current)};
  const visibility=()=>{visible.current=!document.hidden;reset();if(document.hidden&&sessionRef.current?.slot===0){state.current.paused=true;net.current?.broadcast(state.current)}};
  window.addEventListener("keydown",onKey);window.addEventListener("keyup",onKey);window.addEventListener("blur",reset);document.addEventListener("visibilitychange",visibility);
  return()=>{cancelAnimationFrame(frame);window.removeEventListener("keydown",onKey);window.removeEventListener("keyup",onKey);window.removeEventListener("blur",reset);document.removeEventListener("visibilitychange",visibility)};
 },[]);
 // With a room code in hand (invite link or typed), look the room up so the lobby shows the host's pick
 // on the left and never lets the guest pick the same hero.
 useEffect(()=>{const c=code.trim().toUpperCase();if(session||training||!/^[A-Z2-9]{8}$/.test(c)){setRoom(null);return}let alive=true;const t=setTimeout(()=>{roomRequest({op:"peek",code:c}).then((info:RoomInfo)=>{if(!alive)return;setRoom(info);if(isHero(info.hostHero)){const r=rosterOf(info.hostHero);setRoster(r);setHero(h=>h===info.hostHero||rosterOf(h)!==r?defaultOpponent(info.hostHero):h)}}).catch(()=>{if(alive)setRoom(null)})},250);return()=>{alive=false;clearTimeout(t)}},[code,session,training]);
 useEffect(()=>{if(session||training||arcade)return;const hostHero=room&&isHero(room.hostHero)?room.hostHero:null;state.current=hostHero?createState(hostHero,hero===hostHero?defaultOpponent(hostHero):hero):createState(hero);setView({...state.current})},[hero,session,training,room,arcade]);
 /** Wire a session (fresh or resumed) to the network and the arena. */
 function attach(s:Session){state.current=createState(s.hostHero,s.slot===1?s.hero!:undefined);sessionRef.current=s;rivalId.current=null;snaps.current={prev:null,curr:null,prevAt:0,currAt:0};setSession(s);setTraining(false);trainingRef.current=false;input.current=emptyInput();
  const n=new RoomNetwork(s,()=>{setMembers([...n.members]);setDirect(!!n.direct);setFallback(!n.direct&&n.members.length>1);setOnlineError(n.error);setLatency(n.latency)},snapshot=>{const sn=snaps.current;sn.prev=sn.curr;sn.prevAt=sn.currAt;sn.curr=snapshot;sn.currAt=performance.now();state.current=snapshot;for(const e of snapshot.events||[])audio().play(e)},()=>{state.current.paused=true});net.current=n;
  store.set("session:"+s.code,{s,at:Date.now()});const r=rosterOf(s.hostHero);history.replaceState(null,"","?sala="+s.code+(r!==DEFAULT_ROSTER?"&elenco="+r:""));canvas.current?.focus()}
 async function connect(op:"create"|"join",watch=false,roomCode=code){
  if(!loaded)return;setBusy(true);setError("");
  try{const s:Session=await roomRequest({op,name:name.trim()||(watch?"Visitante":"Jogador"),hero,code:roomCode.trim().toUpperCase(),watch,public:isPublic});attach(s)}
  catch(e){setError(e instanceof Error?e.message:"Não foi possível entrar.")}finally{setBusy(false)}
 }
 function leave(){if(sessionRef.current)store.del("session:"+sessionRef.current.code);if(arcadeRef.current&&arcadeRef.current.result!=="champion")saveRun({...arcadeRef.current,result:"fight"});net.current?.close();net.current=null;sessionRef.current=null;rivalId.current=null;setSession(null);trainingRef.current=false;setTraining(false);arcadeRef.current=null;setArcade(null);if(vsTimer.current){clearTimeout(vsTimer.current);vsTimer.current=null}setVs(null);input.current=emptyInput();state.current=createState(hero);setMembers([]);setOnlineError("");setFallback(false);history.replaceState(null,"",location.pathname+(roster!==DEFAULT_ROSTER?"?elenco="+roster:""))}
 function train(){setError("");arcadeRef.current=null;setArcade(null);trainingRef.current=true;setTraining(true);state.current=createState(hero);input.current=emptyInput();begin(state.current);canvas.current?.focus()}
 // Arcade: fight the rest of the roster in a shuffled order, boss last. Each fight keeps `tick` growing
 // like a rematch would. A VS card introduces the opponent; the countdown starts when it leaves.
 function startFight(arc:Arcade){const t=state.current.tick;state.current=createState(arc.hero,arc.ladder[arc.stage]);state.current.tick=t+1;input.current=emptyInput();arcadeRef.current=arc;setArcade({...arc});setVs({a:arc.hero,b:arc.ladder[arc.stage],stage:arc.stage,total:arc.ladder.length});audio().play("round");if(vsTimer.current)clearTimeout(vsTimer.current);vsTimer.current=setTimeout(()=>{vsTimer.current=null;setVs(null);canvas.current?.focus()},2400)}
 function startArcade(){setError("");trainingRef.current=false;setTraining(false);brain.current=createBrain(Date.now()>>>0,difficulty);store.set("arcade:difficulty",difficulty);startFight({ladder:ladder(hero,brain.current.rng),stage:0,result:"fight",difficulty,losses:0,startedAt:Date.now(),hero})}
 function continueArcade(){if(!saved)return;setError("");trainingRef.current=false;setTraining(false);brain.current=createBrain(Date.now()>>>0,saved.difficulty);setHero(saved.hero);setDifficulty(saved.difficulty);startFight({...saved,result:"fight",startedAt:Date.now()-(saved.startedAt||0)})}
 function nextFight(){const arc=arcadeRef.current;if(!arc)return;startFight({...arc,stage:arc.stage+1,result:"fight"})}
 function retryFight(){const arc=arcadeRef.current;if(!arc)return;startFight({...arc,result:"fight"})}
 /** After every fight the run is saved (stage to resume, elapsed time so far); a title clears it and enters the records. */
 function saveRun(arc:Arcade){const r=rosterOf(arc.hero);const elapsed=Date.now()-arc.startedAt;
  if(arc.result==="champion"){store.del("arcade:progress:"+r);const list=store.get<Record_[]>("arcade:records:"+r,[]);list.push({hero:arc.hero,losses:arc.losses,time:elapsed,difficulty:arc.difficulty,date:Date.now()});list.sort((a,b)=>a.losses-b.losses||a.time-b.time);store.set("arcade:records:"+r,list.slice(0,5))}
  else store.set("arcade:progress:"+r,{...arc,stage:Math.min(arc.ladder.length-1,arc.result==="won"?arc.stage+1:arc.stage),result:"fight",startedAt:elapsed});
 }
 async function copy(watch:boolean){if(!session)return;const url=location.origin+location.pathname+"?sala="+session.code+(watch?"&assistir=1":"")+(roster!==DEFAULT_ROSTER?"&elenco="+roster:"");try{await navigator.clipboard.writeText(url);setCopied(watch?"Link para assistir copiado!":"Convite copiado!");setTimeout(()=>setCopied(""),2500)}catch{setCopied("Código da sala: "+session.code)}}
 // Shared by keyboard and touch: taps on jump/attacks stay pressed for at least 120 ms so the
 // 60 Hz simulation and the 33 ms lossy network send both get to see them.
 function action(key:keyof Input,down:boolean){held.current[key]=down;if(down&&["jump","punch","kick","special","grab"].includes(key))pulse.current[key]=performance.now()+120;input.current[key]=down||performance.now()<(pulse.current[key]||0);net.current?.sendInput(input.current)}
 const isSpectator=session?.slot===null,host=session?.slot===0;
 const beaten=(i:number)=>!!arcade&&(i<arcade.stage||(i===arcade.stage&&arcade.result!=="fight"&&arcade.result!=="lost"));
 const overlay=active&&!vs?(view.phase==="waiting"?"AGUARDANDO RIVAL":view.paused?"PARTIDA PAUSADA":view.phase==="countdown"?String(Math.max(1,Math.ceil(view.clock))):view.phase==="round"?(view.winner===-1?"EMPATE":"K.O."):view.phase==="over"?(arcade?(arcade.result==="lost"?"VOCÊ PERDEU":arcade.result==="champion"?ROSTER_INFO[roster].champion:"VOCÊ VENCEU!"):"VITÓRIA DE "+title(view.fighters[view.winner]?.hero||"marica")):null):null;
 const champion=!!arcade&&arcade.result==="champion"&&view.phase==="over";
 return <main className="app-shell">
  <header className="topbar"><a className="brand" href={roster===DEFAULT_ROSTER?"/":"/?elenco="+roster} aria-label={ROSTER_INFO[roster].title}>{ROSTER_INFO[roster].brand[0]}<span>{ROSTER_INFO[roster].brand[1]}</span></a><span className="edition">FLIPERAMA ONLINE <span>· {ROSTER_INFO[roster].edition}</span></span><button className="sound-button" onClick={()=>setSound(!sound)} aria-pressed={sound}>{sound?"SOM LIGADO":"SOM DESLIGADO"}</button></header>
  <section className="game-layout">
   <div className="arena-column">
    <div className="stage-shell" ref={stage}>
     <div className="hud">
      {[0,1].map((i)=><div key={i} className={"fighter-hud fighter-"+i}><div className="fighter-label"><strong>{title(view.fighters[i].hero)}</strong><span>{members.find(m=>m.slot===i)?.name||(active?(training?(i===1?"ALVO DE TREINO":"VOCÊ"):arcade?(i===0?"VOCÊ":"LUTA "+(arcade.stage+1)+"/"+arcade.ladder.length):"Aguardando…"):room?(i===0?room.hostName:"VOCÊ"):"")}</span></div><div className="health" role="progressbar" aria-label={"Vida de "+title(view.fighters[i].hero)} aria-valuenow={Math.round(view.fighters[i].hp)} aria-valuemin={0} aria-valuemax={view.fighters[i].maxHp||100}><div style={{width:(view.fighters[i].hp/(view.fighters[i].maxHp||100)*100)+"%"}}/></div><div className="round-dots">{[0,1].map(n=><i key={n} className={view.fighters[i].wins>n?"won":""}/>)}</div></div>)}
      <div className="timer"><b>{active?String(Math.ceil(view.timer)).padStart(2,"0"):"99"}</b><span>ROUND {view.round}</span></div>
     </div>
     <canvas ref={canvas} width={960} height={540} tabIndex={0} className="game-canvas" aria-label="Arena de luta. Use WASD para movimentar, J para soco, K para chute, L para defesa, U para agarrão e I para especial."/>
     {!loaded&&<div className="game-overlay"><b>CARREGANDO ARENA…</b></div>}
     {loaded&&!active&&<div className="attract"><span>{title(view.fighters[0].hero)} <em>vs</em> {title(view.fighters[1].hero)}</span><p>{room?"Sala de "+room.hostName+". Você luta do lado direito.":"Escolha seu lado. Convide seu rival."}</p></div>}
     {vs&&<div className="vs-screen" role="status"><div><img src={portrait(vs.a)} alt=""/><strong>{title(vs.a)}</strong><small>VOCÊ</small></div><b>VS</b><div><img src={portrait(vs.b)} alt=""/><strong>{title(vs.b)}</strong><small>{isBoss(vs.b)?"CHEFE":"LUTA "+(vs.stage+1)+" DE "+vs.total}</small></div><span className="vs-stage">{ROSTER_INFO[roster].caption} · {DIFFICULTIES.find(d=>d.id===(arcade?.difficulty||difficulty))?.name}</span></div>}
     {champion&&!vs&&<div className="game-overlay result ending"><img src={portrait(arcade!.hero)} alt=""/><b>{ROSTER_INFO[roster].champion}</b><p>{CHARACTERS[arcade!.hero].ending}</p><p>{arcade!.ladder.length} adversários · {arcade!.losses} derrota(s) · {clock(Date.now()-arcade!.startedAt)}</p><button className="primary-button" onClick={leave}>VOLTAR AO INÍCIO</button></div>}
     {overlay&&!champion&&<div className={"game-overlay "+(view.phase==="over"?"result":"")}><b>{overlay}</b>{view.phase==="waiting"&&<p>Compartilhe o convite com o segundo jogador.</p>}{view.paused&&view.phase!=="waiting"&&<p>Os dois jogadores precisam manter a arena aberta.</p>}{view.phase==="over"&&(host||training)&&<button className="primary-button" onClick={()=>{rematch(state.current);input.current=emptyInput()}}>JOGAR NOVAMENTE</button>}{view.phase==="over"&&arcade&&(arcade.result==="won"?<><p>Próximo: {title(arcade.ladder[arcade.stage+1])}{isBoss(arcade.ladder[arcade.stage+1])?", o chefe":""}</p><button className="primary-button" onClick={nextFight}>PRÓXIMA LUTA</button></>:arcade.result==="lost"?<><p>{title(arcade.ladder[arcade.stage])} levou essa. Tente de novo.</p><button className="primary-button" onClick={retryFight}>TENTAR DE NOVO</button></>:null)}</div>}
     <div className="energy-hud">{view.fighters.map((f,i)=><div key={i} className={"energy-side energy-"+i}><div className={"energy "+(f.energy>=60?"charged":"")}><div style={{width:f.energy+"%"}}/></div><span>{f.energy>=60?"ESPECIAL PRONTO":CHARACTERS[f.hero].special.toUpperCase()}</span></div>)}</div>
    </div>
    <div className="stage-caption"><span>{ROSTER_INFO[roster].caption} <span className="caption-divider">/</span> MELHOR DE 3</span><button onClick={()=>stage.current?.requestFullscreen?.()} aria-label="Abrir arena em tela cheia">TELA CHEIA ⛶</button></div>
    {active&&!isSpectator&&<div className="touch-controls" aria-label="Controles de toque"><div className="dpad">{([["jump","↑"],["left","←"],["down","↓"],["right","→"]] as const).map(([key,label])=><button key={key} aria-label={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);action(key,true)}} onPointerUp={()=>action(key,false)} onPointerCancel={()=>action(key,false)}>{label}</button>)}</div><div className="touch-attacks">{([["punch","SOCO"],["kick","CHUTE"],["grab","AGARRÃO"],["block","DEFESA"],["special","ESPECIAL"]] as const).map(([key,label])=><button key={key} onPointerDown={e=>{e.currentTarget.setPointerCapture(e.pointerId);action(key,true)}} onPointerUp={()=>action(key,false)} onPointerCancel={()=>action(key,false)}>{label}</button>)}</div></div>}
    <footer className="controls-bar"><span><kbd>A D</kbd> andar</span><span><kbd>W</kbd> pular</span><span><kbd>S</kbd> abaixar</span><span><kbd>J</kbd> soco</span><span><kbd>K</kbd> chute</span><span><kbd>U</kbd> agarrão</span><span><kbd>L</kbd> defesa</span><span><kbd>I</kbd> especial</span></footer>
   </div>
   <aside className="lobby">
    {!active?<><p className="eyebrow">ENTRE NA LUTA</p><h1>Escolha seu<br/>personagem.</h1><div className="roster-switch" role="group" aria-label="Elenco">{(Object.keys(ROSTER_INFO) as Roster[]).map(r=><button key={r} aria-pressed={roster===r} className={roster===r?"selected":""} disabled={!!room||!loaded} title={room?"O elenco é definido pela sala":undefined} onClick={()=>chooseRoster(r)}>{ROSTER_INFO[r].name.toUpperCase()}</button>)}</div><div className={"hero-options "+(heroesOf(roster).length>8?"many":"")}>{heroesOf(roster).map(h=><button key={h} aria-pressed={hero===h} className={hero===h?"selected":""} disabled={room?.hostHero===h} title={room?.hostHero===h?"Já escolhido por "+room.hostName:undefined} onClick={()=>setHero(h)}><img className="hero-thumb" src={portrait(h,true)} alt="" loading="lazy"/><span className="hero-text"><span className="hero-number">{CHARACTERS[h].number}</span>{title(h)}</span></button>)}</div><div className={"special-info "+hero}><div className="fighter-card"><img src={portrait(hero)} alt="" className="card-portrait"/><div className="card-body"><span>{styleOf(hero)}{isBoss(hero)?" · CHEFE":""}</span><div className="stat-bars">{([["VIDA",statsOf(hero).hp/120],["VELOCIDADE",(statsOf(hero).speed-.8)/.45],["FORÇA",(statsOf(hero).power-.85)/.3]] as const).map(([label,v])=><div key={label}><small>{label}</small><i><b style={{width:Math.round(Math.max(.12,Math.min(1,v))*100)+"%"}}/></i></div>)}</div><span>GOLPE ESPECIAL</span><strong style={{color:CHARACTERS[hero].color}}>{CHARACTERS[hero].special}</strong><p>{CHARACTERS[hero].description}</p></div></div><p className="story">{CHARACTERS[hero].story}</p></div><div className="roster-switch mode-switch" role="group" aria-label="Modo de jogo"><button aria-pressed={mode==="arcade"} className={mode==="arcade"?"selected":""} disabled={!!room} title={room?"Você recebeu um convite para um duelo":undefined} onClick={()=>setMode("arcade")}>ARCADE</button><button aria-pressed={mode==="duelo"} className={mode==="duelo"?"selected":""} onClick={()=>setMode("duelo")}>DUELO ONLINE</button></div>
     {mode==="arcade"?<><p className="mode-hint">Enfrente todos do elenco em ordem aleatória, cada um mais difícil que o anterior{ROSTER_INFO[roster].boss?", e o chefe por último":""}.</p><div className="roster-switch difficulty-switch" role="group" aria-label="Dificuldade">{DIFFICULTIES.map(d=><button key={d.id} aria-pressed={difficulty===d.id} className={difficulty===d.id?"selected":""} title={d.hint} onClick={()=>{setDifficulty(d.id);store.set("arcade:difficulty",d.id)}}>{d.name}</button>)}</div><button className="primary-button" disabled={!loaded} onClick={startArcade}>JOGAR ARCADE<span>▶</span></button>{saved&&<button className="continue-button" disabled={!loaded} onClick={continueArcade}>CONTINUAR · {title(saved.hero)} · LUTA {saved.stage+1}/{saved.ladder.length}</button>}<button className="training-link" disabled={!loaded} onClick={train}>Testar os controles sozinho</button>
      {records.length>0&&<div className="records"><span className="field-label">MELHORES CORRIDAS</span>{records.slice(0,3).map((r,i)=><div className="member" key={i}><span className="player-tag">{i+1}</span><div><strong>{title(r.hero)}</strong><small>{r.losses} derrota(s) · {clock(r.time)} · {DIFFICULTIES.find(d=>d.id===r.difficulty)?.name.toLowerCase()}</small></div></div>)}</div>}</>
     :<><label className="field-label" htmlFor="nickname">Seu apelido</label><input id="nickname" value={name} maxLength={20} onChange={e=>setName(e.target.value)} placeholder="Como a turma te chama?" autoComplete="nickname"/><button className="primary-button" disabled={busy||!loaded} onClick={()=>connect("create")}>{busy?"CONECTANDO…":"CRIAR SALA"}<span>＋</span></button><label className="public-toggle"><input type="checkbox" checked={isPublic} onChange={e=>setIsPublic(e.target.checked)}/>Listar a sala para quem chegar sozinho</label><div className="or-divider"><span>JÁ TEM UM CÓDIGO?</span></div><label className="sr-only" htmlFor="room-code">Código da sala</label><input id="room-code" className="code-input" value={code} maxLength={8} onChange={e=>setCode(e.target.value.toUpperCase().replace(/[^A-Z2-9]/g,""))} placeholder="CÓDIGO DA SALA" autoComplete="off"/><div className="join-actions"><button disabled={busy||code.length!==8||!loaded||!!room?.rivalName} onClick={()=>connect("join")}>ENTRAR NA LUTA</button><button disabled={busy||code.length!==8||!loaded} onClick={()=>connect("join",true)}>ASSISTIR</button></div><p className="join-hint">{room?(room.rivalName?"Os dois lugares já estão ocupados. Você ainda pode assistir.":room.hostName+" já escolheu "+title(room.hostHero)+". Escolha o seu lutador e entre."):"Escolha seu lutador antes de entrar. Cada personagem ocupa uma vaga."}</p>
      <div className="room-list"><span className="field-label">SALAS ABERTAS</span>{openRooms.length===0?<p className="empty">Nenhuma sala esperando rival agora. Crie a sua.</p>:openRooms.map(r=><button key={r.code} onClick={()=>setCode(r.code)} aria-label={"Entrar na sala de "+r.hostName}><img src={portrait(r.hostHero,true)} alt=""/><span>{r.hostName} · {title(r.hostHero)}</span><small>{ROSTER_INFO[r.roster].name}</small></button>)}</div></>}</>:<>
     <p className="eyebrow">{training?"AQUECIMENTO":arcade?"MODO ARCADE":isSpectator?"ARQUIBANCADA":"VOCÊ ESTÁ NA ARENA"}</p><h1>{training?"Modo treino.":arcade?"Luta "+(arcade.stage+1)+" de "+arcade.ladder.length+".":isSpectator?"Só na torcida.":title(session!.hero!)+ "."}</h1>
     {arcade&&<><p>Vença dois rounds para avançar. A ordem é sorteada a cada partida e cada adversário reage mais rápido e defende melhor que o anterior. Dificuldade {DIFFICULTIES.find(d=>d.id===arcade.difficulty)?.name.toLowerCase()}; o progresso fica salvo neste navegador.</p><div className="room-members"><span className="field-label">ADVERSÁRIOS</span>{arcade.ladder.map((h,i)=><div className={"member "+(beaten(i)?"beaten":i===arcade.stage?"current":"")} key={h}><span className="player-tag">{beaten(i)?"✓":i+1}</span><div><strong>{title(h)}</strong><small>{(isBoss(h)?"chefe · ":"")+(beaten(i)?"vencido":i===arcade.stage?"agora":"em breve")}</small></div></div>)}</div></>}
     {session&&<><label className="field-label">CÓDIGO DA SALA</label><div className="room-code-display">{session.code}</div><div className="connection-label"><span className={onlineError?"connection-bad":"connection-good"}/>{onlineError?"Reconectando…":members.length<2?"Sala aberta":direct?"Conexão direta":"Conexão pela sala"}{direct&&<small>{latency} ms*</small>}</div><p className="connection-note">{direct?"* Tempo de resposta da sala.":fallback?"Conexão alternativa ativa; pode haver mais atraso.":"Envie o convite para começar."}</p><button className="primary-button" onClick={()=>copy(false)}>CONVIDAR RIVAL<span>↗</span></button><button className="secondary-button" onClick={()=>copy(true)}>COPIAR LINK PARA ASSISTIR</button><div className="copy-note" role="status">{copied}</div><div className="room-members"><span className="field-label">NA SALA</span>{[0,1].map(i=><div className="member" key={i}><span className="player-tag">P{i+1}</span><div><strong>{members.find(m=>m.slot===i)?.name||"Aguardando rival"}</strong><small>{title(view.fighters[i].hero)}</small></div></div>)}<div className="spectator-count">{members.filter(m=>m.slot===null).length} espectador(es) · até 20</div></div><p className="connection-note">Se a página recarregar, você volta para esta sala por até 15 minutos.</p></>}
     {training&&<><p>O rival fica parado para você experimentar os golpes. Use a barra de energia para testar o especial e encadeie soco, soco e chute.</p><button className="secondary-button" onClick={()=>{const t=state.current.tick;state.current=createState(hero);state.current.tick=t+1;begin(state.current)}}>REINICIAR TREINO</button></>}
     {!isSpectator&&<div className="quick-tip"><kbd>I</kbd><span>O especial usa 60 de energia. Ela recarrega durante a luta.<br/><kbd>U</kbd> agarra quem só defende.</span></div>}
     <button className="leave-button" onClick={leave}>{training?"VOLTAR":arcade?"SAIR (PROGRESSO SALVO)":"SAIR DA SALA"}</button></>}
    {error&&<p className="error-message" role="alert">{error}</p>}{onlineError&&<p className="error-message" role="status">{onlineError}</p>}
   </aside>
  </section>
  <div className="bottom-note"><span>{ROSTER_INFO[roster].title.toUpperCase()}</span><span>WASD + J K U L I · Teclado recomendado</span></div>
 </main>
}
